#ifndef VELOCITY_TO_POSITION_COMMAND_CONTROLLER__VELOCITY_TO_POSITION_COMMAND_CONTROLLER_HPP_
#define VELOCITY_TO_POSITION_COMMAND_CONTROLLER__VELOCITY_TO_POSITION_COMMAND_CONTROLLER_HPP_

#include <atomic>
#include <functional>
#include <memory>
#include <mutex>
#include <string>
#include <thread>
#include <unordered_map>
#include <vector>

#include "controller_interface/chainable_controller_interface.hpp"
#include "hector_ros_controllers_msgs/msg/sync_status.hpp"
#include "rclcpp/subscription.hpp"
#include "rclcpp_action/rclcpp_action.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_buffer.hpp"
#include "realtime_tools/realtime_publisher.hpp"
#include "realtime_tools/realtime_thread_safe_box.hpp"
#include "sensor_msgs/msg/joint_state.hpp"
#include "std_msgs/msg/bool.hpp"
#include "std_msgs/msg/float64_multi_array.hpp"
#include "urdf_parser/urdf_parser.h"
#include "velocity_to_position_command_controller/sync_pair_manager.hpp"

#include "velocity_to_position_command_controller/trapezoidal_profile.hpp"

// auto-generated by generate_parameter_library
#include <hector_ros_controllers/velocity_to_position_command_controller_parameters.hpp>

#include <hector_ros_controllers_msgs/action/drive_flipper_group.hpp>
#include <hector_ros_controllers_msgs/action/sync_flipper_group.hpp>

namespace velocity_to_position_command_controller
{
using CmdType = std_msgs::msg::Float64MultiArray;
using DriveFlipperGroupAction = hector_ros_controllers_msgs::action::DriveFlipperGroup;
using DriveFlipperGroupGoalHandle = rclcpp_action::ServerGoalHandle<DriveFlipperGroupAction>;
using SyncFlipperGroupAction = hector_ros_controllers_msgs::action::SyncFlipperGroup;
using SyncFlipperGroupGoalHandle = rclcpp_action::ServerGoalHandle<SyncFlipperGroupAction>;

enum MoveState {
  MOVING,
  STOPPING,
  STOPPED,
};

enum class GroupActionState {
  IDLE,
  EXECUTING,
  COMPLETED,
  CANCELLED,
};

/// RT-safe command for a group action (written from non-RT, read in update loop)
struct GroupActionCommand {
  bool active = false;
  std::vector<TrapezoidalProfile> joint_profiles; ///< one per joint in group
  rclcpp::Time start_time;
  double target_position = 0.0; ///< common target (for feedback)
};

/**
 * \brief Velocity-to-position command controller for a set of joints.
 *
 * Receives velocity references (from a chaining controller or topic subscription)
 * and converts them to position commands using feedforward integration with
 * velocity-tracking PD control and optional joint synchronization.
 *
 * Subscribes to:
 * - \b commands (std_msgs::msg::Float64MultiArray) : The velocity commands to apply.
 */
class VelocityToPositionCommandController : public controller_interface::ChainableControllerInterface
{
public:
  VelocityToPositionCommandController();

  ~VelocityToPositionCommandController() override = default;

  controller_interface::InterfaceConfiguration command_interface_configuration() const override;

  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  controller_interface::CallbackReturn on_init() override;

  controller_interface::CallbackReturn
  on_configure( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::CallbackReturn
  on_activate( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::CallbackReturn
  on_deactivate( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::return_type
  update_and_write_commands( const rclcpp::Time &time, const rclcpp::Duration &period ) override;

  bool on_set_chained_mode( bool chained_mode ) override;

protected:
  std::vector<hardware_interface::CommandInterface> on_export_reference_interfaces() override;

  controller_interface::return_type
  update_reference_from_subscribers( const rclcpp::Time &time,
                                     const rclcpp::Duration &period ) override;

private:
  // URDF joint limit parsing
  void parse_joint_limits_from_urdf();

  // Parameter utilities
  void declare_parameters();
  controller_interface::CallbackReturn read_parameters();

  // State reading
  void update_joint_states_if_valid();

  // State machine
  void update_move_states( double vel_command, size_t joint_idx, const rclcpp::Time &time );

  // Synchronization
  void update_sync_states( const std::vector<double> &vel_commands );
  void update_sync_offsets();
  void reset_sync_offsets( size_t joint_idx );
  double sync_pd_control( size_t joint_idx, double vel_command );

  // Control law
  double pos_pd_control( size_t joint_idx, double vel_command, const rclcpp::Duration &period );
  double position_control( size_t joint_idx, double vel_command, const rclcpp::Duration &period );

  // Dynamic parameter reconfiguration
  rcl_interfaces::msg::SetParametersResult set_pid_gains( const rclcpp::Parameter &p );

  // Joint configuration
  std::vector<std::string> joints_;
  std::vector<std::string> reference_interface_names_;
  std::vector<std::string> command_interface_types_;
  std::vector<std::string> state_interface_types_;

  // Joint state caching
  std::vector<double> joint_position_states_;
  std::vector<double> joint_velocity_states_;

  // Position tracking
  std::vector<double> desired_positions_;
  std::vector<double> hold_positions_;

  // State machine
  std::vector<MoveState> move_states_;
  double stopping_vel_threshold_;
  double max_velocity_;
  double max_acceleration_;
  double max_deceleration_;

  // Braking profiles (per synchronous group, or per ungrouped joint)
  std::vector<TrapezoidalProfile> braking_profiles_;
  std::vector<rclcpp::Time> braking_start_times_;

  // Synchronization
  SyncPairManager sync_pairs_;
  std::vector<bool> sync_states_;
  std::vector<std::string> joint_groups_;
  std::unordered_map<std::string, std::vector<size_t>> groups_;

  // E-stop
  std::string e_stop_topic_;
  realtime_tools::RealtimeBuffer<bool> e_stop_active_;
  bool interfaces_valid_;

  // PID gains
  double kp_;
  double kd_;
  double kp_sync_;
  double kd_sync_;
  double sync_velocity_factor_;
  double sync_velocity_min_threshold_;

  // Parameter callbacks
  std::shared_ptr<rclcpp::ParameterCallbackHandle> cb_handle_kp_;
  std::shared_ptr<rclcpp::ParameterCallbackHandle> cb_handle_kd_;
  std::shared_ptr<rclcpp::ParameterCallbackHandle> cb_handle_sync_kp_;
  std::shared_ptr<rclcpp::ParameterCallbackHandle> cb_handle_sync_kd_;
  std::shared_ptr<rclcpp::ParameterCallbackHandle> cb_handle_sync_velocity_factor_;
  std::shared_ptr<rclcpp::ParameterCallbackHandle> cb_handle_sync_velocity_min_threshold_;
  std::shared_ptr<rclcpp::ParameterCallbackHandle> cb_handle_max_velocity_;
  std::shared_ptr<rclcpp::ParameterCallbackHandle> cb_handle_max_acceleration_;
  std::shared_ptr<rclcpp::ParameterCallbackHandle> cb_handle_max_deceleration_;
  std::shared_ptr<rclcpp::ParameterEventHandler> param_subscriber_;

  // Debug publishers (realtime-safe, pre-allocated messages)
  void publish_debug_joint_state_in();
  void publish_debug_joint_state_out( const std::vector<double> &positions );
  void publish_sync_status( const std::vector<double> &vel_commands_out );
  void update_debug_publishers( bool enable );
  std::atomic<bool> debug_pubs_enabled_{ false }; ///< RT-safe flag checked in update loop
  realtime_tools::RealtimePublisherSharedPtr<sensor_msgs::msg::JointState> rt_debug_in_js_pub_;
  realtime_tools::RealtimePublisherSharedPtr<sensor_msgs::msg::JointState> rt_debug_out_js_pub_;
  realtime_tools::RealtimePublisherSharedPtr<hector_ros_controllers_msgs::msg::SyncStatus> rt_sync_status_pub_;
  std::shared_ptr<rclcpp::ParameterCallbackHandle> cb_handle_debug_pubs_;

  // Velocity command timeout
  double velocity_command_timeout_;
  rclcpp::Time last_command_time_;

  // RT-safe command buffer and subscriptions
  realtime_tools::RealtimeBuffer<std::shared_ptr<CmdType>> rt_buffer_ptr_;
  rclcpp::Subscription<CmdType>::SharedPtr cmd_sub_;
  rclcpp::Subscription<std_msgs::msg::Bool>::SharedPtr hard_estop_sub_;

  // Parameters
  std::shared_ptr<ParamListener> param_listener_;
  Params params_;

  // Per-joint position limits (NaN if no limits apply, e.g. continuous joints)
  std::vector<double> joint_lower_limits_;
  std::vector<double> joint_upper_limits_;

  // Group action infrastructure
  std::unordered_map<std::string, size_t> group_index_map_; ///< group name -> index in group_actions_
  std::vector<std::string> group_names_;                    ///< ordered group names
  std::vector<realtime_tools::RealtimeBuffer<GroupActionCommand>> rt_group_action_cmds_;
  std::vector<std::atomic<GroupActionState>> group_action_states_;

  // RT-safe snapshot of joint position states for use by non-RT monitor threads (action feedback).
  // Written from update_and_write_commands() via try_set, read from monitor_group_actions().
  realtime_tools::RealtimeThreadSafeBox<std::vector<double>> rt_joint_position_snapshot_;

  // Action servers
  rclcpp_action::Server<DriveFlipperGroupAction>::SharedPtr drive_flipper_action_server_;
  rclcpp_action::Server<SyncFlipperGroupAction>::SharedPtr sync_flipper_action_server_;

  // Action callbacks
  rclcpp_action::GoalResponse
  handle_drive_goal( const rclcpp_action::GoalUUID &uuid,
                     std::shared_ptr<const DriveFlipperGroupAction::Goal> goal );
  rclcpp_action::CancelResponse
  handle_drive_cancel( std::shared_ptr<DriveFlipperGroupGoalHandle> goal_handle );
  void handle_drive_accepted( std::shared_ptr<DriveFlipperGroupGoalHandle> goal_handle );

  rclcpp_action::GoalResponse
  handle_sync_goal( const rclcpp_action::GoalUUID &uuid,
                    std::shared_ptr<const SyncFlipperGroupAction::Goal> goal );
  rclcpp_action::CancelResponse
  handle_sync_cancel( std::shared_ptr<SyncFlipperGroupGoalHandle> goal_handle );
  void handle_sync_accepted( std::shared_ptr<SyncFlipperGroupGoalHandle> goal_handle );

  // Action helpers

  /// Start a group action: compute per-joint profiles and write to RT buffer.
  /// target_positions maps joint index -> target position (one per joint in the group).
  /// Returns empty string on success, error message on failure.
  std::string start_group_action( const std::string &group_name,
                                  const std::vector<double> &target_positions_per_joint,
                                  double max_vel, double max_accel );

  /// Cancel all actions for the given group indices via RT buffer.
  void cancel_group_actions( const std::vector<size_t> &group_indices );

  /// Monitor loop for group actions. Polls state at 20 Hz.
  /// Calls on_complete/on_cancel/on_abort/on_feedback.
  /// on_feedback receives (progress, group_indices) per cycle.
  using MonitorCompleteFn = std::function<void()>;
  using MonitorAbortFn = std::function<void( const std::string &reason )>;
  using MonitorFeedbackFn = std::function<void( double progress )>;
  void monitor_group_actions( const std::vector<size_t> &group_indices,
                              std::function<bool()> is_canceling, MonitorCompleteFn on_complete,
                              MonitorAbortFn on_abort, MonitorFeedbackFn on_feedback );

  /// Process active group actions in update loop
  bool process_group_actions( const rclcpp::Time &time );

  // Action monitoring threads. Each thread sets its `done` flag at the end so
  // finished threads can be joined and erased opportunistically (rather than
  // accumulating until on_deactivate).
  struct MonitorThread {
    std::thread thread;
    std::shared_ptr<std::atomic<bool>> done;
  };
  std::vector<MonitorThread> action_monitor_threads_;
  std::mutex action_monitor_threads_mutex_;
  void reap_finished_monitor_threads(); ///< Join+erase threads that signaled done.
  void cleanup_monitor_threads();       ///< Join+erase all threads (used on deactivate).
};

} // namespace velocity_to_position_command_controller

#endif // VELOCITY_TO_POSITION_COMMAND_CONTROLLER__VELOCITY_TO_POSITION_COMMAND_CONTROLLER_HPP_
