#ifndef VELOCITY_TO_POSITION_COMMAND_CONTROLLER__VELOCITY_TO_POSITION_COMMAND_CONTROLLER_HPP_
#define VELOCITY_TO_POSITION_COMMAND_CONTROLLER__VELOCITY_TO_POSITION_COMMAND_CONTROLLER_HPP_

#include <memory>
#include <string>
#include <unordered_map>
#include <vector>

#include "controller_interface/chainable_controller_interface.hpp"
#include "rclcpp/subscription.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_buffer.hpp"
#include "std_msgs/msg/bool.hpp"
#include "std_msgs/msg/float64_multi_array.hpp"

// auto-generated by generate_parameter_library
#include <hector_ros_controllers/velocity_to_position_command_controller_parameters.hpp>

namespace velocity_to_position_command_controller
{
using CmdType = std_msgs::msg::Float64MultiArray;

enum MoveState {
  MOVING,
  STOPPING,
  STOPPED,
};

/**
 * \brief Velocity-to-position command controller for a set of joints.
 *
 * Receives velocity references (from a chaining controller or topic subscription)
 * and converts them to position commands using feedforward integration with
 * velocity-tracking PD control and optional joint synchronization.
 *
 * Subscribes to:
 * - \b commands (std_msgs::msg::Float64MultiArray) : The velocity commands to apply.
 */
class VelocityToPositionCommandController : public controller_interface::ChainableControllerInterface
{
public:
  VelocityToPositionCommandController();

  ~VelocityToPositionCommandController() override = default;

  controller_interface::InterfaceConfiguration command_interface_configuration() const override;

  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  controller_interface::CallbackReturn on_init() override;

  controller_interface::CallbackReturn
  on_configure( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::CallbackReturn
  on_activate( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::CallbackReturn
  on_deactivate( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::return_type
  update_and_write_commands( const rclcpp::Time &time, const rclcpp::Duration &period ) override;

  bool on_set_chained_mode( bool chained_mode ) override;

protected:
  std::vector<hardware_interface::CommandInterface> on_export_reference_interfaces() override;

  controller_interface::return_type
  update_reference_from_subscribers( const rclcpp::Time &time,
                                     const rclcpp::Duration &period ) override;

private:
  // Parameter utilities
  void declare_parameters();
  controller_interface::CallbackReturn read_parameters();

  // State reading
  void update_joint_states_if_valid();

  // State machine
  void update_move_states( double vel_command, size_t joint_idx );

  // Synchronization
  void update_sync_states( const std::vector<double> &vel_commands );
  void update_sync_offsets();
  double sync_p_control( size_t joint_idx );

  // Control law
  double pos_pd_control( size_t joint_idx, double vel_command, const rclcpp::Duration &period );
  double position_control( size_t joint_idx, double vel_command, const rclcpp::Duration &period );

  // Dynamic parameter reconfiguration
  rcl_interfaces::msg::SetParametersResult set_pid_gains( const rclcpp::Parameter &p );

  // Joint configuration
  std::vector<std::string> joints_;
  std::vector<std::string> reference_interface_names_;
  std::vector<std::string> command_interface_types_;
  std::vector<std::string> state_interface_types_;

  // Joint state caching
  std::vector<double> joint_position_states_;
  std::vector<double> joint_velocity_states_;

  // Position tracking
  std::vector<double> desired_positions_;
  std::vector<double> hold_positions_;

  // State machine
  std::vector<MoveState> move_states_;
  double stopping_vel_threshold_;

  // Synchronization
  std::vector<std::vector<double>> sync_offsets_;
  std::vector<bool> sync_states_;
  std::vector<std::string> joint_groups_;
  std::unordered_map<std::string, std::vector<size_t>> groups_;
  std::vector<std::vector<size_t>> synced_joints_;

  // E-stop
  std::string e_stop_topic_;
  realtime_tools::RealtimeBuffer<bool> e_stop_active_;
  bool interfaces_valid_;

  // PID gains
  double kp_;
  double kd_;
  double kp_sync_;

  // Parameter callbacks
  std::shared_ptr<rclcpp::ParameterCallbackHandle> cb_handle_kp_;
  std::shared_ptr<rclcpp::ParameterCallbackHandle> cb_handle_kd_;
  std::shared_ptr<rclcpp::ParameterCallbackHandle> cb_handle_sync_kp_;
  std::shared_ptr<rclcpp::ParameterEventHandler> param_subscriber_;

  // RT-safe command buffer and subscriptions
  realtime_tools::RealtimeBuffer<std::shared_ptr<CmdType>> rt_buffer_ptr_;
  rclcpp::Subscription<std_msgs::msg::Bool>::SharedPtr hard_estop_sub_;

  // Parameters
  std::shared_ptr<ParamListener> param_listener_;
  Params params_;
};

} // namespace velocity_to_position_command_controller

#endif // VELOCITY_TO_POSITION_COMMAND_CONTROLLER__VELOCITY_TO_POSITION_COMMAND_CONTROLLER_HPP_
