#ifndef WAYPOINT_CONTROLLER_BASE__WAYPOINT_CONTROLLER_BASER_HPP_
#define WAYPOINT_CONTROLLER_BASE__WAYPOINT_CONTROLLER_BASER_HPP_

#include <boost/shared_ptr.hpp>
#include <float.h>
#include <memory>
#include <string>
#include <urdf_parser/urdf_parser.h>
#include <vector>

#include "controller_interface/controller_interface.hpp"
#include "rclcpp/subscription.hpp"
#include "rclcpp_action/rclcpp_action.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_buffer.hpp"
#include "std_msgs/msg/float64_multi_array.hpp"

#include <hector_ros_controllers_msgs/action/waypoint_navigation.hpp>

// auto-generated by generate_parameter_library
// #include <hector_ros_controllers/waypoint_controller_base_parameters.hpp>

namespace waypoint_controller_base
{

struct Goal {
  double x;
  double y;
};

struct MoveCommand {
  double linear_vel_cmd;
  double angual_vel_cmd;
};

struct Pose {
  double x;
  double y;
  double heading;
};

class WaypointControllerBase : public controller_interface::ControllerInterface
{
public:
  WaypointControllerBase();

  ~WaypointControllerBase() = default;

  controller_interface::InterfaceConfiguration command_interface_configuration() const override;

  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  controller_interface::CallbackReturn on_init() override;

  controller_interface::CallbackReturn
  on_configure( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::CallbackReturn
  on_activate( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::CallbackReturn
  on_deactivate( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::return_type update( const rclcpp::Time &time,
                                            const rclcpp::Duration &period ) override;

  virtual MoveCommand computeCommand( const Goal &goal, const Pose &pose,
                                      const double &curr_linear_vel, const double &curr_angular_vel );

  virtual bool check_goal_completion( const Goal &goal, const Pose &pose );

protected:
  void declare_parameters();

  controller_interface::CallbackReturn read_parameters();

  std::vector<std::string> command_interface_types_;
  std::vector<std::string> state_interface_types_;
  std::string interface_type_;

  rclcpp_action::Server<hector_ros_controllers_msgs::action::WaypointNavigation>::SharedPtr navigation_server_;

  // std::shared_ptr<ParamListener> param_listener_;
  // Params params_;

  realtime_tools::RealtimeBuffer<std::shared_ptr<std::vector<Goal>>> trajectory_;
  realtime_tools::RealtimeBuffer<std::shared_ptr<bool>> trajectory_is_active_;
  realtime_tools::RealtimeBuffer<std::shared_ptr<bool>> reset_trajectory_;

  size_t current_goal_idx_;
  Goal current_goal_;
  MoveCommand current_cmd_;
};

} // namespace waypoint_controller_base

#endif // HPP
