#ifndef WAYPOINT_CONTROLLER_BASE__WAYPOINT_CONTROLLER_BASE_HPP_
#define WAYPOINT_CONTROLLER_BASE__WAYPOINT_CONTROLLER_BASE_HPP_

#include <boost/shared_ptr.hpp>
#include <float.h>
#include <memory>
#include <string>
#include <urdf_parser/urdf_parser.h>
#include <vector>

#include "controller_interface/controller_interface.hpp"
#include "rclcpp/subscription.hpp"
#include "rclcpp_action/rclcpp_action.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_buffer.hpp"
#include "realtime_tools/realtime_double_buffer.hpp"
#include "realtime_tools/realtime_server_goal_handle.hpp"
#include "std_msgs/msg/float64_multi_array.hpp"
#include "tf2/exceptions.h"
#include "tf2/utils.h"
#include "tf2_ros/buffer.h"
#include "tf2_ros/transform_listener.h"

#include "geometry_msgs/msg/twist_stamped.hpp"
#include "lifecycle_msgs/msg/state.hpp"
#include "tf2_geometry_msgs/tf2_geometry_msgs.hpp"
#include <hector_ros_controllers_msgs/action/waypoint_navigation.hpp>

// auto-generated by generate_parameter_library
#include <hector_ros_controllers/waypoint_controller_base_parameters.hpp>

namespace waypoint_controller_base
{

struct Waypoint {

  Waypoint()
  {
    x = 0.0;
    y = 0.0;
  }

  Waypoint( const geometry_msgs::msg::Point &point )
  {
    x = point.x;
    y = point.y;
  }

  double x;
  double y;
};

struct MoveCommand {
  double linear_vel_cmd;
  double angual_vel_cmd;
};

struct Pose {
  Pose() { }
  Pose( double x_val, double y_val, double heading_val )
      : x( x_val ), y( y_val ), heading( heading_val )
  {
  }
  double x;
  double y;
  double heading;
};

using WaypointNav = typename hector_ros_controllers_msgs::action::WaypointNavigation;
using RtGhWayNav =
    realtime_tools::RealtimeServerGoalHandle<hector_ros_controllers_msgs::action::WaypointNavigation>;

class WaypointControllerBase : public controller_interface::ControllerInterface
{
public:
  WaypointControllerBase();

  ~WaypointControllerBase() = default;

  controller_interface::InterfaceConfiguration command_interface_configuration() const override;

  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  controller_interface::CallbackReturn on_init() override;

  controller_interface::CallbackReturn
  on_configure( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::CallbackReturn
  on_activate( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::CallbackReturn
  on_deactivate( const rclcpp_lifecycle::State &previous_state ) override;

  rclcpp_action::CancelResponse goal_cancelled_callback(
      const std::shared_ptr<rclcpp_action::ServerGoalHandle<WaypointNav>> goal_handle );

  rclcpp_action::GoalResponse goal_received_callback( const rclcpp_action::GoalUUID &,
                                                      std::shared_ptr<const WaypointNav::Goal> goal );

  void
  goal_accepted_callback( std::shared_ptr<rclcpp_action::ServerGoalHandle<WaypointNav>> goal_handle );

  controller_interface::return_type update( const rclcpp::Time &time,
                                            const rclcpp::Duration &period ) override;

protected:
  virtual MoveCommand computeCommand( const Waypoint &goal, const Pose &pose,
                                      const double &curr_linear_vel, const double &curr_angular_vel );

  virtual bool check_goal_completion( const Waypoint &goal, const Pose &pose );

private:
  bool validate_trajectory( const std::vector<geometry_msgs::msg::Point> &trajectory );

  void update_pose_cb();

  controller_interface::CallbackReturn read_parameters();

  bool set_base_velocities( const MoveCommand &cmd );

  bool stop_base();

  void preempt_active_goal( std::shared_ptr<waypoint_controller_base::RtGhWayNav> active_trajectory );

  void update_feedback();

  WaypointNav::Result get_result_msg( bool success, const std::string &failure_report );

  // Parameters
  bool use_cmd_vel_;
  std::chrono::milliseconds action_monitor_period_;
  std::string tf_prefix_;
  std::string base_link_frame_;
  double goal_completion_tolerance_;

  std::vector<std::string> command_interface_types_;
  std::vector<std::string> state_interface_types_;
  std::string interface_type_;

  rclcpp_action::Server<hector_ros_controllers_msgs::action::WaypointNavigation>::SharedPtr navigation_server_;

  // Updated via Non-RT thread
  realtime_tools::RealtimeBuffer<std::shared_ptr<const WaypointNav::Goal>> trajectory_buffer_;
  realtime_tools::RealtimeBuffer<std::shared_ptr<RtGhWayNav>> trajectory_gh_buffer_;

  // Accessed only by RT thread
  std::shared_ptr<const WaypointNav::Goal> active_trajectory_;
  std::shared_ptr<RtGhWayNav> active_gh_;

  std::shared_ptr<waypoint_controller_base_parameters::ParamListener> param_listener_;
  waypoint_controller_base_parameters::Params params_;

  // canceled_is only managed by Non-RT thread, active_ only by RT thread
  // This prevents logical race conditions
  std::atomic<bool> canceled_;
  bool active_;

  std::atomic<bool> reset_trajectory_;
  size_t current_goal_idx_;

  Waypoint current_goal_;
  MoveCommand current_cmd_;
  realtime_tools::RealtimeBuffer<Pose> current_pose_;

  realtime_tools::RealtimeDoubleBuffer<WaypointNav::Feedback> feedback_buffer_;

  std::shared_ptr<rclcpp::Publisher<geometry_msgs::msg::TwistStamped>> vel_pub_{ nullptr };

  std::shared_ptr<tf2_ros::TransformListener> tf_listener_{ nullptr };
  std::unique_ptr<tf2_ros::Buffer> tf_buffer_;
  rclcpp::TimerBase::SharedPtr pose_update_timer_{ nullptr };

  // Monitors action goal status
  rclcpp::TimerBase::SharedPtr action_monitor_timer_{ nullptr };
};

} // namespace waypoint_controller_base

#endif // HPP
