#pragma once

#include <vector>
#include <string>
#include <deque>

#include <controller_interface/chainable_controller_interface.hpp>
#include <hardware_interface/loaned_command_interface.hpp>
#include <hardware_interface/loaned_state_interface.hpp>
#include <rclcpp/rclcpp.hpp>

// auto-generated by generate_parameter_library
#include <hector_ros_controllers/input_shaping_controller_parameters.hpp>

namespace input_shaping_controller
{

enum class ShaperType {
  NONE,
  ZV,
  ZVD
};

/**
 * @brief Input Shaper implementation for reducing residual vibrations.
 *
 * Input shaping works by convolving the reference command with a sequence of impulses.
 * For a system modeled as a second-order underdamped oscillator with natural frequency (f)
 * and damping ratio (zeta), the damped natural frequency is omega_d = 2 * pi * f * sqrt(1 - zeta^2).
 * 
 * The fundamental delay time between impulses is half the damped period: dt = pi / omega_d.
 * The vibration decay factor over this half-period is K = exp(-zeta * pi / sqrt(1 - zeta^2)).
 *
 * Zero Vibration (ZV) Shaper (2 impulses):
 * - A1 at t=0 : 1 / (1 + K)
 * - A2 at t=dt: K / (1 + K)
 *
 * Zero Vibration Derivative (ZVD) Shaper (3 impulses) - more robust to parameter errors:
 * - A1 at t=0   : 1 / (1 + 2K + K^2)
 * - A2 at t=dt  : 2K / (1 + 2K + K^2)
 * - A3 at t=2*dt: K^2 / (1 + 2K + K^2)
 * 
 * In discrete time, the delay time is converted to an integer number of steps,
 * and past inputs are stored in a history buffer.
 */
struct Shaper {
  ShaperType type = ShaperType::NONE;
  double A1 = 0.0, A2 = 0.0, A3 = 0.0;
  size_t delay_steps = 0;
  std::deque<double> history;
  bool history_initialized = false;

  void init(ShaperType t, double f, double zeta, double dt) {
    type = t;
    if (type == ShaperType::NONE) return;

    const double K = std::exp(-zeta * M_PI / std::sqrt(1.0 - zeta * zeta));
    const double omega_d = 2.0 * M_PI * f * std::sqrt(1.0 - zeta * zeta);
    const double delay_time = M_PI / omega_d;
    
    delay_steps = static_cast<size_t>(std::round(delay_time / dt));
    
    if (type == ShaperType::ZV) {
      const double denom = 1.0 + K;
      A1 = 1.0 / denom;
      A2 = K / denom;
      A3 = 0.0;
      history.resize(delay_steps, 0.0);
    } else if (type == ShaperType::ZVD) {
      const double denom = 1.0 + 2.0 * K + K * K;
      A1 = 1.0 / denom;
      A2 = 2.0 * K / denom;
      A3 = K * K / denom;
      history.resize(2 * delay_steps, 0.0);
    }
  }

  double process(double input) {
    if (std::isnan(input)) {
      return input;
    }
    if (type == ShaperType::NONE) {
      return input;
    }
    if (!history_initialized) {
      reset(input);
      history_initialized = true;
    }
    
    history.push_front(input);
    
    double output = 0.0;
    if (type == ShaperType::ZV) {
      history.pop_back();
      output = A1 * input + A2 * history.back();
    } else if (type == ShaperType::ZVD) {
      history.pop_back();
      output = A1 * input + A2 * history[delay_steps - 1] + A3 * history.back();
    }
    return output;
  }
  
  void reset(double initial_value) {
    std::fill(history.begin(), history.end(), initial_value);
    history_initialized = true;
  }
};

/**
 * @brief Chained-only input shaping controller.
 *
 * - Receives position commands from previous controllers in the chain.
 * - Forwards position commands to its output interfaces after applying input shaping.
 */
class InputShapingController final : public controller_interface::ChainableControllerInterface
{
public:
  InputShapingController();

  controller_interface::CallbackReturn on_init() override;

  controller_interface::CallbackReturn
  on_configure( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::CallbackReturn
  on_activate( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::CallbackReturn
  on_deactivate( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::InterfaceConfiguration command_interface_configuration() const override;

  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  std::vector<hardware_interface::CommandInterface> on_export_reference_interfaces() override;

  controller_interface::return_type
  update_reference_from_subscribers( const rclcpp::Time &time,
                                     const rclcpp::Duration &period ) override;

  controller_interface::return_type
  update_and_write_commands( const rclcpp::Time &time, const rclcpp::Duration &period ) override;

  bool on_set_chained_mode( bool chained_mode ) override;

private:
  // ---- Parameters ----
  std::shared_ptr<ParamListener> param_listener_;
  Params params_;

  // ---- Internal state ----
  bool is_chained_ = true;
  bool shapers_initialized_ = false;
  std::vector<Shaper> shapers_;
};

} // namespace input_shaping_controller
