// Copyright (c) 2023, PAL Robotics
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef SELF_COLLISION_AVOIDANCE_CONTROLLER__SELF_COLLISION_AVOIDANCE_CONTROLLER_HPP_
#define SELF_COLLISION_AVOIDANCE_CONTROLLER__SELF_COLLISION_AVOIDANCE_CONTROLLER_HPP_

// system
#include <chrono>
#include <limits>
#include <memory>
#include <string>
#include <urdf_parser/urdf_parser.h>
#include <vector>

#include "ad_kinematics/tree.h"
#include "boost/shared_ptr.hpp"
#include "controller_interface/chainable_controller_interface.hpp"
#include "fcl/geometry/collision_geometry.h"
#include "fcl/narrowphase/collision.h"
#include "geometry_msgs/msg/transform.hpp"
#include "realtime_tools/realtime_buffer.hpp"
#include "std_msgs/msg/float64_multi_array.hpp"
#include "std_msgs/msg/string.hpp"
// #include "visualization_msgs/msg/marker.hpp"
#include <srdfdom/model.h>

// auto-generated by generate_parameter_library
#include <hector_ros_controllers/self_collision_avoidance_controller_parameters.hpp>

namespace self_collision_avoidance_controller
{
using DataType = std_msgs::msg::Float64MultiArray;

typedef std::tuple<std::shared_ptr<fcl::CollisionObjectd>, std::shared_ptr<fcl::Transform3d>, int>
    CollisionPrimitive;

class SelfCollisionAvoidanceController : public controller_interface::ChainableControllerInterface
{
public:
  controller_interface::CallbackReturn on_init() override;

  controller_interface::InterfaceConfiguration command_interface_configuration() const override;

  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  controller_interface::CallbackReturn
  on_configure( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::CallbackReturn
  on_activate( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::CallbackReturn
  on_deactivate( const rclcpp_lifecycle::State &previous_state ) override;

  bool on_set_chained_mode( bool chained_mode ) override;

  controller_interface::return_type
  update_and_write_commands( const rclcpp::Time &time, const rclcpp::Duration &period ) override;

protected:
  std::vector<hardware_interface::CommandInterface> on_export_reference_interfaces() override;

  controller_interface::return_type
  update_reference_from_subscribers( const rclcpp::Time &time,
                                     const rclcpp::Duration &period ) override;

  std::shared_ptr<fcl::CollisionGeometry<double>>
  urdf_geom_to_fcl_geom( const std::shared_ptr<const urdf::Geometry> &urdf_geom ) const;

  static fcl::Transform3d pose_to_fcl_transform( const urdf::Pose &urdf_pose );

  static fcl::Transform3d
  geom_transform_to_fcl_transform( const geometry_msgs::msg::Transform &transform );

  static fcl::Transform3d
  kinematics_transform_to_fcl_transform( const ad_kinematics::Transform<double> &transform );

  static fcl::Transform3d create_fcl_transform_from_data( double quat_w, double quat_x,
                                                          double quat_y, double quat_z, double t_x,
                                                          double t_y, double t_z );

  fcl::Transform3d get_transform_from_base_link( const std::string &link ) const;

  static bool
  pairwise_primitive_collision_check( const std::vector<CollisionPrimitive> &dependent_link_colls,
                                      const std::vector<CollisionPrimitive> &pot_coll_link_colls,
                                      const fcl::Transform3d &base_to_dependent_link,
                                      const fcl::Transform3d &pot_coll_link_to_base );

  bool write_valid_reference_commands( std::vector<bool> &collision_results );

  bool block_joint( const size_t &joint_idx );

  std::shared_ptr<ParamListener> param_listener_;
  Params params_;

  // Params
  std::vector<std::string> controlled_joints_;
  std::vector<std::string> interface_types_;
  std::map<std::string, std::string> joint_groups_;
  std::map<std::string, std::vector<size_t>> group_joints_;
  double safety_margin_ = 0.01;
  double velocity_look_ahead_factor_ = 1.0;

  std::shared_ptr<ad_kinematics::Tree> transformTree_;
  std::vector<std::string> active_joints_;
  std::vector<int> q_indices_controlled_;
  std::vector<int> q_indices_active_;
  std::vector<std::vector<std::string>> controlled_joint_dependent_links_;
  std::map<std::string, std::set<std::string>> potentially_colliding_links_;

  srdf::Model srdf_;
  bool srdf_received_ = false;

  std::vector<double> joint_angles_;
  std::vector<double> prev_command_vals_;

  std::map<std::string, std::vector<CollisionPrimitive>> link_collision_primitives_;

  realtime_tools::RealtimeBuffer<std::shared_ptr<DataType>> rt_buffer_ptr_;
  rclcpp::Subscription<DataType>::SharedPtr joints_cmd_sub_;
  rclcpp::Subscription<std_msgs::msg::String>::SharedPtr semantic_description_sub;

  std::vector<std::string> reference_interface_names_;
  std::vector<std::string> command_interface_names_;

private:
  controller_interface::CallbackReturn process_params();

  void update_joint_angles();

  void get_dependent_links_from_joint( const urdf::ModelInterfaceSharedPtr &urdf,
                                       const urdf::JointConstSharedPtr &joint,
                                       std::vector<std::string> &dependent_links );

  void get_dependent_links_from_link( const urdf::ModelInterfaceSharedPtr &urdf,
                                      const urdf::LinkConstSharedPtr &link,
                                      std::vector<std::string> &dependent_links );

  void set_joint_infos( const urdf::ModelInterfaceSharedPtr &urdf );

  void set_dependent_links( const urdf::ModelInterfaceSharedPtr &urdf );

  void set_potentially_colliding_links( urdf::ModelInterfaceSharedPtr urdf );

  void collect_collision_primitives( const urdf::ModelInterfaceSharedPtr &urdf );

  /*
  void modify_debug_marker( int id, const fcl::Transform3d &t, std::string link_name,
                            std::shared_ptr<fcl::CollisionGeometry<double>> geom );

  void create_debug_marker( int id, std::shared_ptr<urdf::Geometry> urdf_geom );

  void log_transform( const fcl::Transform3d &t, const std::string title );
    */
};
} // namespace self_collision_avoidance_controller

#endif