#ifndef SAFETY_FORWARD_CONTROLLER__SAFETY_FORWARD_CONTROLLER_HPP_
#define SAFETY_FORWARD_CONTROLLER__SAFETY_FORWARD_CONTROLLER_HPP_

#include <boost/shared_ptr.hpp>
#include <float.h>
#include <memory>
#include <string>
#include <urdf_parser/urdf_parser.h>
#include <vector>

#include "controller_interface/controller_interface.hpp"
#include "rclcpp/subscription.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_buffer.hpp"
#include "std_msgs/msg/float64_multi_array.hpp"

// auto-generated by generate_parameter_library
#include <hector_ros_controllers/safety_forward_controller_parameters.hpp>

namespace safety_forward_controller
{
using CmdType = std_msgs::msg::Float64MultiArray;

class SafetyForwardController : public controller_interface::ControllerInterface
{
public:
  SafetyForwardController();

  ~SafetyForwardController() = default;

  controller_interface::InterfaceConfiguration command_interface_configuration() const override;

  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  controller_interface::CallbackReturn on_init() override;

  controller_interface::CallbackReturn
  on_configure( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::CallbackReturn
  on_activate( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::CallbackReturn
  on_deactivate( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::return_type update( const rclcpp::Time &time,
                                            const rclcpp::Duration &period ) override;

protected:
  void declare_parameters();

  controller_interface::CallbackReturn read_parameters();

  std::vector<std::string> joints_;
  std::vector<std::shared_ptr<urdf::JointLimits>> joint_limits_;

  std::vector<std::string> command_interface_types_;
  std::vector<std::string> state_interface_types_;
  std::string interface_type_;

  bool safety_engaged_ = false;
  int safty_timer_period_ms_;
  rclcpp::TimerBase::SharedPtr safety_timer_;

  realtime_tools::RealtimeBuffer<std::shared_ptr<CmdType>> rt_command_ptr_;
  rclcpp::Subscription<CmdType>::SharedPtr joints_command_subscriber_;

  std::shared_ptr<ParamListener> param_listener_;
  Params params_;
};

} // namespace safety_forward_controller

#endif // HPP
