//
// Created by aljoscha-schmidt on 7/17/25.
//

#ifndef APPLY_CURRENT_LIMIT_CONTROLLER_HPP
#define APPLY_CURRENT_LIMIT_CONTROLLER_HPP
#include "controller_interface/chainable_controller_interface.hpp"
#include <memory>
#include <string>
#include <urdf_parser/urdf_parser.h>
#include <vector>

#include "controller_interface/controller_interface.hpp"
#include "rclcpp/subscription.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_buffer.hpp"
#include "std_msgs/msg/bool.hpp"
#include "std_msgs/msg/float64_multi_array.hpp"
#include "std_srvs/srv/set_bool.hpp"

// auto-generated by generate_parameter_library
#include <hector_ros_controllers/apply_current_limit_controller_parameters.hpp>

namespace apply_current_limit_controller
{
using DataType = std_msgs::msg::Float64MultiArray;
class ApplyCurrentLimitController : public controller_interface::ChainableControllerInterface
{
public:
  ApplyCurrentLimitController();

  ~ApplyCurrentLimitController() = default;

public:
  controller_interface::CallbackReturn on_init() override;

  controller_interface::InterfaceConfiguration command_interface_configuration() const override;

  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  controller_interface::CallbackReturn
  on_configure( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::CallbackReturn
  on_activate( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::CallbackReturn
  on_deactivate( const rclcpp_lifecycle::State &previous_state ) override;

  bool on_set_chained_mode( bool chained_mode ) override;

  controller_interface::return_type
  update_and_write_commands( const rclcpp::Time &time, const rclcpp::Duration &period ) override;

protected:
  controller_interface::CallbackReturn process_params();

  std::vector<hardware_interface::CommandInterface> on_export_reference_interfaces() override;
  std::vector<hardware_interface::StateInterface> on_export_state_interfaces() override;

  controller_interface::return_type
  update_reference_from_subscribers( const rclcpp::Time &time,
                                     const rclcpp::Duration &period ) override;

  std::vector<std::string> joints_;
  std::vector<std::string> command_interface_types_;
  std::vector<std::string> state_interface_types_;
  std::vector<std::string> command_interface_names_;
  std::vector<std::string> exposed_state_interface_names_;
  std::vector<std::string> reference_interface_names_;

  std::vector<double> compliant_limits_;
  std::vector<double> stiff_limits_;
  std::atomic<bool> compliance_enabled_;

  std::atomic<bool> e_stop_active_{ false };
  bool chained_mode_;

  realtime_tools::RealtimeBuffer<std::shared_ptr<DataType>> rt_buffer_ptr_;
  rclcpp::Subscription<std_msgs::msg::Bool>::SharedPtr soft_estop_sub_;

  rclcpp::Service<std_srvs::srv::SetBool>::SharedPtr enable_compliant_limits_srv_;

  std::shared_ptr<ParamListener> param_listener_;
  Params params_;
};

} // namespace apply_current_limit_controller

#endif // APPLY_CURRENT_LIMIT_CONTROLLER_HPP
