#pragma once

#include <controller_interface/chainable_controller_interface.hpp>
#include <safety_position_controller/collision_checker.hpp>
#include <std_msgs/msg/string.hpp>
#include <std_srvs/srv/set_bool.hpp>
#include <urdf_model/joint.h>

// auto-generated by generate_parameter_library
#include <hector_ros_controllers/safety_position_controller_parameters.hpp>
namespace safety_position_controller
{

class SafetyPositionController final : public controller_interface::ChainableControllerInterface
{
public:
  SafetyPositionController();

  controller_interface::CallbackReturn on_init() override;
  controller_interface::CallbackReturn
  on_configure( const rclcpp_lifecycle::State &previous_state ) override;
  controller_interface::CallbackReturn
  on_activate( const rclcpp_lifecycle::State &previous_state ) override;
  controller_interface::CallbackReturn
  on_deactivate( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::InterfaceConfiguration command_interface_configuration() const override;
  controller_interface::InterfaceConfiguration state_interface_configuration() const override;
  std::vector<hardware_interface::CommandInterface> on_export_reference_interfaces() override;

  controller_interface::return_type
  update_reference_from_subscribers( const rclcpp::Time &time,
                                     const rclcpp::Duration &period ) override;
  controller_interface::return_type
  update_and_write_commands( const rclcpp::Time &time, const rclcpp::Duration &period ) override;

  bool on_set_chained_mode( bool chained_mode ) override;

private:
  enum class JointType { CONTINUOUS, REVOLUTE_BOUNDED, PRISMATIC_BOUNDED, FIXED, OTHER };

  // Internal helpers
  static double unwrap_to_nearest( double current, double target );
  double clamp( size_t i, double value ) const;
  bool parse_urdf_and_fill_joint_info( const std::string &urdf_xml );
  bool gather_interface_indices();
  bool wait_for_srdf();

  // ---- Variables ----
  bool is_chained_ = true;
  bool in_compliant_mode_ = false;

  // ---- State ----
  std::vector<int> state_interface_index_;

  // ---- URDF-based joint info ----
  std::vector<JointType> kinds_;                       // in order of params_.joints
  std::vector<bool> has_limits_;                       // in order of params_.joints
  std::vector<double> lower_limits_;                   // in order of params_.joints
  std::vector<double> upper_limits_;                   // in order of params_.joints
  std::vector<double> velocity_limits_;                // in order of params_.joints
  std::vector<double> max_allowed_distance_per_cycle_; // in order of params_.joints

  std::vector<std::string> all_joint_names_;
  std::unordered_map<std::string, double> cc_positions_; // for collision checker

  std::vector<double> cmd_positions_;
  std::vector<double> current_positions_;

  // Params
  std::shared_ptr<ParamListener> param_listener_;
  std::shared_ptr<rclcpp::ParameterEventHandler> param_subscriber_;
  Params params_;

  // ---- Collision checker ----
  std::unique_ptr<CollisionChecker> collision_checker_;
  std::string srdf_;
  bool srdf_received_ = false;

  // ros communication
  rclcpp::Service<std_srvs::srv::SetBool>::SharedPtr enforce_current_limits_service_;
  rclcpp::Subscription<std_msgs::msg::String>::SharedPtr semantic_description_sub_;
};

} // namespace safety_position_controller
