#pragma once

#include <controller_interface/chainable_controller_interface.hpp>
#include <safety_position_controller/collision_checker.hpp>
#include <std_msgs/msg/string.hpp>
#include <std_srvs/srv/set_bool.hpp>
#include <urdf_model/joint.h>

// auto-generated by generate_parameter_library
#include <hector_ros_controllers/safety_position_controller_parameters.hpp>

namespace safety_position_controller
{

/**
 * @brief Chained-only safety controller.
 *
 * - Enforces joint limits (pos/vel), optional unwrapping for continuous joints.
 * - Optional self-collision check via CollisionChecker (URDF + SRDF).
 * - Optional current-limit control (stiff/compliant) toggled by service.
 *   - Assumes actuator uses current values as limits in position control mode.
 * - Subscribes to SRDF on "robot_description_semantic" (transient local).
 */
class SafetyPositionController final : public controller_interface::ChainableControllerInterface
{
public:
  /// @brief Ctor; controller is chainable-only by design.
  SafetyPositionController();

  /**
   * @brief Initialize parameters, SRDF subscriber, and (optionally) collision checker.
   * @return CallbackReturn::SUCCESS on success, else ::ERROR
   */
  controller_interface::CallbackReturn on_init() override;

  /**
   * @brief Configure with current parameters; waits for SRDF if needed, builds CC.
   * @param previous_state lifecycle state (unused)
   * @return SUCCESS/ERROR
   */
  controller_interface::CallbackReturn
  on_configure( const rclcpp_lifecycle::State &previous_state ) override;

  /**
   * @brief Activate controller; validates interfaces, updates params, prepares limits.
   * Reloads dynamic parameters. -> Controllers must be deactivated/reactivated to apply changes!
   * @param previous_state lifecycle state (unused)
   * @return SUCCESS/ERROR
   */
  controller_interface::CallbackReturn
  on_activate( const rclcpp_lifecycle::State &previous_state ) override;

  /**
   * @brief Deactivate controller (no special action).
   * @param previous_state lifecycle state (unused)
   * @return SUCCESS
   */
  controller_interface::CallbackReturn
  on_deactivate( const rclcpp_lifecycle::State &previous_state ) override;

  /**
   * @brief Request command interfaces.
   * - Always: <joint>/position
   * - Optional: <joint>/current (if current-limit control enabled)
   */
  controller_interface::InterfaceConfiguration command_interface_configuration() const override;

  /**
   * @brief Request state interfaces.
   * - All non-fixed joints: <joint>/position (needed for CC and unwrapping)
   */
  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  /**
   * @brief Export per-joint reference interfaces (position) for chaining.
   * @return vector of CommandInterface referencing internal reference buffers
   */
  std::vector<hardware_interface::CommandInterface> on_export_reference_interfaces() override;

  /**
   * @brief Chained-only: no direct subscribers, just return OK.
   */
  controller_interface::return_type
  update_reference_from_subscribers( const rclcpp::Time &time,
                                     const rclcpp::Duration &period ) override;

  /**
   * @brief Main step: read states → enforce limits → (optional) block-if-too-far
   * → (optional) set current limits → (optional) self-collision check → write commands.
   * @return OK on success; ERROR if read/write failed
   */
  controller_interface::return_type
  update_and_write_commands( const rclcpp::Time &time, const rclcpp::Duration &period ) override;

  /**
   * @brief Enable/disable chained mode.
   * @note Controller is intended to run chained; non-chained falls back to hold.
   */
  bool on_set_chained_mode( bool chained_mode ) override;

private:
  /// @brief Joint type classification used for limit/unwrap logic.
  enum class JointType { CONTINUOUS, REVOLUTE_BOUNDED, PRISMATIC_BOUNDED, FIXED, OTHER };

  /**
   * @brief Read current joint positions for configured joints.
   * @return true if all reads succeeded
   */
  bool read_current_positions();

  /**
   * @brief Write per-joint position commands (NaN entries are skipped).
   * @param commands commanded positions (size == params_.joints.size())
   * @return true if all writes succeeded (for non-NaN entries)
   */
  bool write_position_commands( const std::vector<double> &commands );

  /**
   * @brief Apply unwrap/clamp rules to references → fill cmd_positions_.
   */
  void enforce_limits();

  /**
   * @brief Limit per-cycle motion by vel_limit/update_rate (scaled).
   * Reduces command toward current position if excessive.
   */
  void block_if_too_far();

  /**
   * @brief Write current-limit commands (stiff/compliant) if enabled.
   * @return true if all writes succeed
   */
  bool write_current_limits();

  /**
   * @brief Unwrap target angle to the nearest equivalent around current.
   * @param current current angle [rad]
   * @param target target angle (wrapped) [rad]
   * @return unwrapped target near current
   */
  static double unwrap_to_nearest( double current, double target );

  /**
   * @brief Clamp value to [lower, upper] (with validity checks); logs on clamp.
   * @param i joint index in params_.joints
   * @param value requested value
   * @return clamped value
   */
  double clamp( size_t i, double value ) const;

  /**
   * @brief Parse URDF, collect joint names (non-fixed) and limits for params_.joints.
   * @param urdf_xml URDF as XML string
   * @return true on success
   */
  bool parse_urdf_and_fill_joint_info( const std::string &urdf_xml );

  /**
   * @brief Map requested state interfaces to indices (position).
   * @return true if all indices were found
   */
  bool gather_interface_indices();

  /**
   * @brief Wait for SRDF on "robot_description_semantic" (bounded attempts).
   * @return true if received before timeout
   */
  bool wait_for_srdf();

  // ---- Configuration / mode ----
  bool is_chained_ = true;         ///< chained-only controller (hold if false)
  bool in_compliant_mode_ = false; ///< selects compliant vs. stiff current limits

  // ---- Interface bookkeeping ----
  std::vector<int> state_interface_index_; ///< index in state_interfaces_ per params_.joints

  // ---- URDF-based joint info ----
  std::vector<JointType> kinds_;                       // in order of params_.joints
  std::vector<bool> has_limits_;                       // in order of params_.joints
  std::vector<double> lower_limits_;                   // in order of params_.joints
  std::vector<double> upper_limits_;                   // in order of params_.joints
  std::vector<double> velocity_limits_;                // in order of params_.joints
  std::vector<double> max_allowed_distance_per_cycle_; // in order of params_.joints

  // ---- Collision checking context ----
  std::vector<std::string> all_joint_names_;             ///< all non-fixed joint names (state)
  std::unordered_map<std::string, double> cc_positions_; ///< name→position map for CC
  std::unique_ptr<CollisionChecker> collision_checker_;  ///< optional self-collision checker
  std::string srdf_;                                     ///< SRDF XML (semantic)
  bool srdf_received_ = false;                           ///< latched SRDF received

  // ---- Command/state buffers (aligned with params_.joints) ----
  std::vector<double> cmd_positions_;     ///< post-enforcement commands
  std::vector<double> current_positions_; ///< latest measured positions
  bool on_hold_{ false };                 ///< non-chained fallback
  std::vector<double> hold_positions_;    ///< positions to hold when not chained

  // ---- Parameters ----
  std::shared_ptr<ParamListener> param_listener_;
  std::shared_ptr<rclcpp::ParameterEventHandler> param_subscriber_;
  Params params_;

  // ---- ROS I/F ----
  rclcpp::Service<std_srvs::srv::SetBool>::SharedPtr
      enforce_current_limits_service_; ///< toggles compliant mode
  rclcpp::Subscription<std_msgs::msg::String>::SharedPtr
      semantic_description_sub_;                    ///< SRDF (transient local)
  static constexpr int throttle_logging_msg = 2000; ///< ms; throttle for WARN/ERROR logs
};

} // namespace safety_position_controller
