#pragma once

#include <atomic>
#include <limits>
#include <memory>
#include <string>
#include <vector>

#include <controller_interface/chainable_controller_interface.hpp>
#include <realtime_tools/realtime_buffer.hpp>
#include <safety_position_controller/collision_checker.hpp>
#include <safety_position_controller/collision_observer.hpp>
#include <safety_position_controller/joint_info.hpp>
#include <safety_position_controller/safety_diagnostics.hpp>
#include <safety_position_controller/safety_pipeline.hpp>
#include <std_msgs/msg/bool.hpp>
#include <std_msgs/msg/float64_multi_array.hpp>
#include <std_msgs/msg/string.hpp>
#include <std_srvs/srv/set_bool.hpp>

// auto-generated by generate_parameter_library
#include <hector_ros_controllers/safety_position_controller_parameters.hpp>

namespace safety_position_controller
{
using CmdType = std_msgs::msg::Float64MultiArray;
/**
 * @brief Chainable safety controller between a position reference and the hardware.
 *
 * ROS-facing shell around the ROS-free SafetyPipeline (velocity/acceleration limits,
 * collision damper QP, deviation boxes, stall/park). Collision observation lives in
 * CollisionObserver, status/debug publishing in SafetyDiagnostics.
 *
 * References come from either source; in both cases the checked (and, where the safety
 * pipeline had to intervene, modified) command is forwarded to the hardware:
 * - chained mode: the exported reference interfaces, written by the upstream controller.
 * - non-chained mode: the "~/commands" topic (Float64MultiArray, one entry per joint).
 * A per-joint NaN reference means "no target": it demands zero velocity, so the joint
 * brakes to a smooth stop and holds.
 *
 * - Enforces joint position/velocity limits; continuous joints take the shortest path.
 * - Optional self-collision check via CollisionChecker (URDF + SRDF).
 * - Optional current-limit control (stiff/compliant) toggled by service.
 *   - Assumes actuator uses current values as limits in position control mode.
 * - Subscribes to SRDF on "robot_description_semantic" (transient local).
 */
class SafetyPositionController final : public controller_interface::ChainableControllerInterface
{
public:
  /// @brief Ctor.
  SafetyPositionController();

  /**
   * @brief Initialize parameters, SRDF subscriber, and (optionally) collision checker.
   * @return CallbackReturn::SUCCESS on success, else ::ERROR
   */
  controller_interface::CallbackReturn on_init() override;

  /**
   * @brief Configure with current parameters; waits for SRDF if needed, builds CC.
   * @param previous_state lifecycle state (unused)
   * @return SUCCESS/ERROR
   */
  controller_interface::CallbackReturn
  on_configure( const rclcpp_lifecycle::State &previous_state ) override;

  /**
   * @brief Activate controller; validates interfaces, updates params, prepares limits.
   * Reloads dynamic parameters. -> Controllers must be deactivated/reactivated to apply changes!
   * @param previous_state lifecycle state (unused)
   * @return SUCCESS/ERROR
   */
  controller_interface::CallbackReturn
  on_activate( const rclcpp_lifecycle::State &previous_state ) override;

  /**
   * @brief Deactivate controller; stops the status timer and clears the engaged E-stop.
   * The subscriptions live for the whole controller lifetime.
   * @param previous_state lifecycle state (unused)
   * @return SUCCESS
   */
  controller_interface::CallbackReturn
  on_deactivate( const rclcpp_lifecycle::State &previous_state ) override;

  /**
   * @brief Request command interfaces.
   * - Always: <joint>/position
   * - Optional: <joint>/current (if current-limit control enabled)
   */
  controller_interface::InterfaceConfiguration command_interface_configuration() const override;

  /**
   * @brief Request state interfaces.
   * - All non-fixed joints: <joint>/position (needed for CC and unwrapping)
   */
  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  /**
   * @brief Export per-joint reference interfaces (position) for chaining.
   * @return vector of CommandInterface referencing internal reference buffers
   */
  std::vector<hardware_interface::CommandInterface> on_export_reference_interfaces() override;

  /**
   * @brief Fill the reference interfaces when NOT in chained mode.
   * Reads the latest "~/commands" message from the realtime buffer; in chained mode the
   * references are written by the upstream controller and this is a no-op.
   */
  controller_interface::return_type
  update_reference_from_subscribers( const rclcpp::Time &time,
                                     const rclcpp::Duration &period ) override;

  /**
   * @brief Main step: read states → safety pipeline (QP)
   * → (optional) set current limits → write commands.
   * @return always OK. A handle locked by another thread (async hardware components)
   * only skips that cycle: ERROR would make the controller manager deactivate this
   * controller together with its whole chain. Configuration faults are caught in
   * on_configure/on_activate instead.
   */
  controller_interface::return_type
  update_and_write_commands( const rclcpp::Time &time, const rclcpp::Duration &period ) override;

  /**
   * @brief Enable/disable chained mode.
   * @note Both modes are supported; the references are simply sourced from the upstream
   * controller (chained) or from the "~/commands" topic (non-chained), selected by
   * is_in_chained_mode(). Switching invalidates the current references so no stale
   * target is resumed.
   */
  bool on_set_chained_mode( bool chained_mode ) override;

private:
  /**
   * @brief Read current joint positions for configured joints.
   * @return false if a state handle was locked by another thread or reported a
   * non-finite position (skip the cycle and hold)
   */
  bool read_current_positions();

  /**
   * @brief Write per-joint position commands (non-finite entries are skipped).
   * A handle locked by another thread is logged and left unwritten: the hardware then
   * keeps the previous command.
   * @param commands commanded positions (size == params_.joints.size())
   */
  void write_position_commands( const std::vector<double> &commands );

  /// Write current-limit commands (stiff/compliant) if the interfaces were claimed.
  void write_current_limits();

  /**
   * @brief Map params_.joints to all_joint_names_ indices for state interface reads.
   * We have len(all_joint_names_) state interfaces, need to find indices for params_.joints.
   * @return true if all indices were found
   */
  bool gather_joint_indices();

  /**
   * @brief Wait for SRDF on "robot_description_semantic" (bounded attempts).
   * @return true if received before timeout
   */
  bool wait_for_srdf();

  /// Publish ~/status via diagnostics with the current controller flags.
  void publish_status();

  /**
   * @brief Build the SafetyPipeline (QP limiter + per-joint limits) from parameters.
   * Called from on_activate.
   * @return true on success
   */
  bool setup_pipeline_on_activate();

  /**
   * @brief Safety pipeline cycle: prepare (desired velocity, boxes, park), collision
   * observation at the commanded configuration, step (solve, integrate, stall/park),
   * write. Translates pipeline/observer events into logs.
   * @return true if an event occurred that the caller should publish a status for
   */
  bool run_safety_pipeline();

  // ---- Configuration / mode ----
  std::atomic<bool> in_compliant_mode_{ false }; ///< selects compliant vs. stiff current limits

  // ---- E-stop ----
  /// Last requested E-stop state. Tracks the external safety signal and therefore
  /// survives deactivation; estop_engaged_ is what the update loop acts on.
  std::atomic<bool> estop_active_{ false };
  std::atomic<bool> estop_engaged_{ false }; ///< actually engaged in update loop

  // ---- Safety bypass (for folded arm positions etc.) ----
  std::atomic<bool> safety_bypass_active_{
      false }; ///< when true, collision checks and strict limits are relaxed
  rclcpp::TimerBase::SharedPtr safety_bypass_timer_; ///< auto re-enables safety checks after timeout
  rclcpp::Service<std_srvs::srv::SetBool>::SharedPtr
      bypass_safety_checks_service_; ///< service to toggle bypass

  // ---- Interface bookkeeping ----
  std::vector<int> joint_index_; ///< index in all_joint_names per params_.joints

  // ---- URDF-based joint info ----
  std::vector<JointInfo> joint_infos_;       ///< in order of params_.joints
  std::vector<std::string> all_joint_names_; ///< all non-fixed joint names (state)

  // ---- Collision checking ----
  std::unique_ptr<CollisionChecker> collision_checker_;   ///< optional self-collision checker
  std::unique_ptr<CollisionObserver> collision_observer_; ///< per-cycle observation + edge state
  std::vector<int> joint_v_index_; ///< maps controlled joint index → pinocchio velocity-space index
  std::string srdf_;               ///< SRDF XML (semantic)
  std::atomic<bool> srdf_received_{ false }; ///< latched SRDF received
  double last_manipulability_{ 0.0 };        ///< latest Yoshikawa manipulability index

  // ---- Command/state buffers (aligned with params_.joints) ----
  std::vector<double> current_positions_; ///< latest measured positions
  std::vector<double> hold_positions_;    ///< positions to hold during E-stop

  // ---- Safety pipeline ----
  std::unique_ptr<SafetyPipeline> pipeline_; ///< ROS-free QP safety pipeline
  std::vector<double> qp_cmd_std_;           ///< write buffer for write_position_commands

  // ---- Diagnostics (status / qp_debug / debug joint states) ----
  std::unique_ptr<SafetyDiagnostics> diagnostics_;

  // ---- Parameters ----
  std::shared_ptr<ParamListener> param_listener_;
  Params params_;

  // ---- ROS I/F ----
  rclcpp::Service<std_srvs::srv::SetBool>::SharedPtr
      enforce_current_limits_service_; ///< toggles compliant mode
  rclcpp::Subscription<std_msgs::msg::String>::SharedPtr
      semantic_description_sub_; ///< SRDF (transient local)

  // Non-chained command input
  realtime_tools::RealtimeBuffer<std::shared_ptr<CmdType>> rt_command_ptr_;
  rclcpp::Subscription<CmdType>::SharedPtr joints_command_subscriber_;

  // E-stop input
  rclcpp::Subscription<std_msgs::msg::Bool>::SharedPtr estop_subscriber_;

  // Periodic status timer
  rclcpp::TimerBase::SharedPtr status_timer_;

  static constexpr int throttle_logging_msg = 10000; ///< ms; throttle for WARN/ERROR logs
};

} // namespace safety_position_controller
