#pragma once

#include <atomic>
#include <cstdint>
#include <limits>
#include <memory>
#include <string>
#include <vector>

#include <rclcpp/rclcpp.hpp>
#include <rclcpp_lifecycle/lifecycle_node.hpp>
#include <realtime_tools/realtime_thread_safe_box.hpp>
#include <sensor_msgs/msg/joint_state.hpp>

#include <safety_position_controller/collision_checker.hpp>
#include <safety_position_controller/safety_pipeline.hpp>

#include <hector_ros_controllers_msgs/msg/safety_position_controller_status.hpp>
#include <hector_ros_controllers_msgs/msg/safety_qp_debug.hpp>

// auto-generated by generate_parameter_library
#include <hector_ros_controllers/safety_position_controller_parameters.hpp>

namespace safety_position_controller
{

/**
 * @brief Status / debug ROS I/O of the SafetyPositionController.
 *
 * Owns the latched ~/status publisher (with a realtime snapshot buffer), the ~/qp_debug
 * introspection publisher, the debug joint-state publishers and their dynamically
 * reconfigurable parameter callbacks, plus the human-readable formatters used in
 * warnings. Pure consumer of pipeline/checker state — never mutates control state.
 */
class SafetyDiagnostics
{
public:
  /// Controller-owned flags read at publish time (they live in atomics on the controller).
  struct StatusFlags {
    bool bypass_active{ false };
    bool compliant_mode{ false };
    bool estop_engaged{ false };
  };

  /**
   * @param node controller node (publishers and parameter callbacks are created on it)
   * @param params reference to the controller's parameter struct (outlives this object)
   * @param checker non-owning collision checker for pair-name resolution; may be null
   */
  SafetyDiagnostics( rclcpp_lifecycle::LifecycleNode::SharedPtr node, const Params &params,
                     const CollisionChecker *checker );

  /// Store the activation-resolved joint names and current limits: publishStatus() runs
  /// on executor threads (status timer, service callbacks) and must not read the
  /// controller's mutable Params fields, which on_activate rewrites in place. Held in a
  /// box because on_activate can run while a service callback publishes.
  void configure( std::vector<std::string> joint_names, std::vector<double> stiff_current_limits,
                  std::vector<double> compliant_current_limits );

  /// Refresh the status snapshot from the control thread. The write always lands, so a
  /// publishStatus() later in the same cycle reports this cycle; blocking is bounded by
  /// a reader's snapshot copy under a priority-inheritance mutex.
  void updateSnapshot( const SafetyPipeline *pipeline, double min_distance,
                       std::size_t num_pairs_in_safety_zone, double manipulability );

  /// Publish ~/status (latched) from the latest snapshot; callable from any thread.
  void publishStatus( const StatusFlags &flags );

  /// Publish per-cycle QP introspection on ~/qp_debug if enabled (dynamic parameter).
  void maybePublishQpDebug( const SafetyPipeline &pipeline,
                            const std::vector<double> &processed_reference );

  /// Debug joint-state echo of the incoming references / outgoing commands (if enabled).
  /// Debug echo of the references this cycle, in the controller's interface kind.
  void publishJointStateIn( const std::vector<double> &values );
  /// Debug echo of the commands written this cycle, in the controller's interface kind.
  void publishJointStateOut( const std::vector<double> &values );

  /// Human-readable per-joint blocked-direction analysis (used in the stall warning).
  std::string formatBlockedDirections( const SafetyPipeline &pipeline ) const;

  /**
   * @brief Format collision-pair info for log warnings: "'a' <-> 'b': 0.0123 m, ...".
   * Filters @p pairs to those with distance <= max_distance; falls back to the single
   * pair at @p fallback_pair_index (or "unknown") if the filtered list is empty.
   */
  std::string formatCollisionPairs( const std::vector<CollisionResult::PairInfo> &pairs,
                                    double max_distance, std::size_t fallback_pair_index ) const;

private:
  /// Debug joint state carrying `values` in the field the interface kind names.
  sensor_msgs::msg::JointState jointStateMessage( const std::vector<double> &values ) const;

  /// Trivially-copyable view of the status fields written from the controller update
  /// thread; see updateSnapshot() for the synchronization contract.
  struct StatusSnapshot {
    double min_distance{ std::numeric_limits<double>::max() };
    double manipulability{ 0.0 };
    uint32_t num_pairs_in_safety_zone{ 0 };
    bool qp_solved{ false };
    bool qp_braking{ false };
    bool qp_push_out_relaxed{ false };
    uint32_t qp_num_collision_constraints{ 0 };
    double qp_solve_time_us{ 0.0 };
    bool stalled{ false };
    bool parked{ false };
  };

  rclcpp_lifecycle::LifecycleNode::SharedPtr node_;
  const Params &params_;
  const CollisionChecker *checker_; ///< non-owning, for pair-name resolution

  /// Activation-resolved values read by publishStatus() (see configure()).
  struct StatusConfig {
    std::vector<std::string> joint_names;
    std::vector<double> stiff_current_limits;
    std::vector<double> compliant_current_limits;
  };
  realtime_tools::RealtimeThreadSafeBox<StatusConfig> config_box_;

  rclcpp::Publisher<hector_ros_controllers_msgs::msg::SafetyPositionControllerStatus>::SharedPtr status_pub_;
  realtime_tools::RealtimeThreadSafeBox<StatusSnapshot> rt_status_box_;

  std::atomic<bool> qp_debug_enabled_{ false };
  rclcpp::Publisher<hector_ros_controllers_msgs::msg::SafetyQpDebug>::SharedPtr qp_debug_pub_;

  std::atomic<bool> debug_js_enabled_{ false };
  rclcpp::Publisher<sensor_msgs::msg::JointState>::SharedPtr debug_in_js_pub_;
  rclcpp::Publisher<sensor_msgs::msg::JointState>::SharedPtr debug_out_js_pub_;

  std::shared_ptr<rclcpp::ParameterEventHandler> param_subscriber_;
  std::shared_ptr<rclcpp::ParameterCallbackHandle> cb_handle_debug_pubs_;
  std::shared_ptr<rclcpp::ParameterCallbackHandle> cb_handle_qp_debug_;
};

} // namespace safety_position_controller
