#ifndef CURRENT_LIMIT_CONTROLLER__CURRENT_LIMIT_CONTROLLER_HPP_
#define CURRENT_LIMIT_CONTROLLER__CURRENT_LIMIT_CONTROLLER_HPP_

#include <boost/shared_ptr.hpp>
#include <float.h>
#include <memory>
#include <string>
#include <urdf_parser/urdf_parser.h>
#include <vector>

#include "controller_interface/controller_interface.hpp"
#include "rclcpp/subscription.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_buffer.hpp"
#include "std_msgs/msg/float64_multi_array.hpp"
#include "std_srvs/srv/set_bool.hpp"

// auto-generated by generate_parameter_library
#include <hector_ros_controllers/current_limit_controller_parameters.hpp>

namespace current_limit_controller
{
using CmdType = std_msgs::msg::Float64MultiArray;

class CurrentLimitController : public controller_interface::ControllerInterface
{
public:
  CurrentLimitController();

  ~CurrentLimitController() = default;

  controller_interface::InterfaceConfiguration command_interface_configuration() const override;

  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  controller_interface::CallbackReturn on_init() override;

  controller_interface::CallbackReturn
  on_configure( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::CallbackReturn
  on_activate( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::CallbackReturn
  on_deactivate( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::return_type update( const rclcpp::Time &time,
                                            const rclcpp::Duration &period ) override;

protected:
  controller_interface::CallbackReturn read_parameters();

  std::vector<std::string> joints_;
  std::vector<std::string> command_interface_names_;

  std::vector<double> compliant_limits_;
  std::vector<double> stiff_limits_;
  std::atomic<bool> compliance_enabled_;

  rclcpp::Service<std_srvs::srv::SetBool>::SharedPtr enable_compliant_limits_srv_;
  std::shared_ptr<ParamListener> param_listener_;
  Params params_;
};

} // namespace current_limit_controller
#endif
