// Copyright (c) 2023, PAL Robotics
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef PASSTHROUGH_CONTROLLER__PASSTHROUGH_CONTROLLER_HPP_
#define PASSTHROUGH_CONTROLLER__PASSTHROUGH_CONTROLLER_HPP_

// system
#include <limits>
#include <memory>
#include <string>
#include <urdf_parser/urdf_parser.h>
#include <vector>
#include <chrono>

#include "ad_kinematics/tree.h"
#include "boost/shared_ptr.hpp"
#include "controller_interface/chainable_controller_interface.hpp"
#include "fcl/geometry/collision_geometry.h"
#include "fcl/narrowphase/collision.h"
#include "realtime_tools/realtime_buffer.hpp"
#include "std_msgs/msg/float64_multi_array.hpp"
#include "tf2/exceptions.h"
#include "tf2_ros/buffer.h"
#include "tf2_ros/transform_listener.h"
#include "visualization_msgs/msg/marker.hpp"

// auto-generated by generate_parameter_library
#include "passthrough_controller_parameters.hpp"

/**
 * PassthroughController is a simple chainable controller that exposes reference interfaces equal to
 * the number of it's command interfaces. This controller simply forwards the information commanded
 * to it's reference interface to it's own command interfaces without any modifications.
 */
namespace passthrough_controller
{
using DataType = std_msgs::msg::Float64MultiArray;

typedef std::tuple<std::shared_ptr<fcl::CollisionObjectd>, std::shared_ptr<fcl::Transform3d>, int>
    CollisionPrimitive;

class PassthroughController : public controller_interface::ChainableControllerInterface
{
public:
  controller_interface::CallbackReturn on_init() override;

  controller_interface::InterfaceConfiguration command_interface_configuration() const override;

  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  controller_interface::CallbackReturn
  on_configure( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::CallbackReturn
  on_activate( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::CallbackReturn
  on_deactivate( const rclcpp_lifecycle::State &previous_state ) override;

  bool on_set_chained_mode( bool chained_mode ) override;

  controller_interface::return_type
  update_and_write_commands( const rclcpp::Time &time, const rclcpp::Duration &period ) override;

protected:
  std::vector<hardware_interface::CommandInterface> on_export_reference_interfaces() override;

  controller_interface::return_type
  update_reference_from_subscribers( const rclcpp::Time &time,
                                     const rclcpp::Duration &period ) override;

  void set_joint_infos( const urdf::ModelInterfaceSharedPtr urdf );

  void set_potentially_colliding_links();

  void collect_collision_primitives( const urdf::ModelInterfaceSharedPtr urdf );

  std::shared_ptr<fcl::CollisionGeometry<double>>
  urdf_geom_to_fcl_geom( std::shared_ptr<const urdf::Geometry> urdf_geom );

  fcl::Transform3d pose_to_fcl_transform( const urdf::Pose &urdf_pose );

  fcl::Transform3d geom_transform_to_fcl_transform( const geometry_msgs::msg::Transform &transform );

  fcl::Transform3d kinematics_transform_to_fcl_transform( const ad_kinematics::Transform<double> &transform );

  fcl::Transform3d create_fcl_transform_from_data( double quat_w, double quat_x, double quat_y,
                                                   double quat_z, double t_x, double t_y,
                                                   double t_z );

  fcl::Transform3d get_transform_from_base_link( std::string &link );

  void modify_debug_marker( int id, const fcl::Transform3d &t, std::string link_name,
                            std::shared_ptr<fcl::CollisionGeometry<double>> geom );

  void create_debug_marker( int id, std::shared_ptr<urdf::Geometry> urdf_geom );

  void log_transform( const fcl::Transform3d &t, const std::string title );

  bool pairwise_primitive_collision_check(
      std::vector<passthrough_controller::CollisionPrimitive> &source_colls,
      std::vector<passthrough_controller::CollisionPrimitive> &target_colls,
      fcl::Transform3d &base_to_child_l, fcl::Transform3d &base_to_target_l );

  void update_joint_angles();

  bool write_valid_reference_commands( std::vector<bool> &collision_results );

  std::shared_ptr<ParamListener> param_listener_;
  Params params_;

  rclcpp::Publisher<visualization_msgs::msg::Marker>::SharedPtr marker_pub_;

  std::vector<std::string> controlled_joints_;
  std::vector<std::string> active_joints_;
  double safety_margin_;

  std::vector<int> q_indices_controlled;
  std::vector<int> q_indices_active;

  std::vector<std::string> joint_child_link_names_;

  std::vector<double> joint_angles_;
  std::vector<std::vector<unsigned long>> potentially_colliding_links_;

  std::map<std::string, std::vector<CollisionPrimitive>> link_collision_primitives_;
  std::shared_ptr<ad_kinematics::Tree> transformTree_;

  realtime_tools::RealtimeBuffer<std::shared_ptr<DataType>> rt_buffer_ptr_;
  rclcpp::Subscription<DataType>::SharedPtr joints_cmd_sub_;

  std::vector<std::string> reference_interface_names_;
  std::vector<std::string> command_interface_names_;
  std::vector<double> prev_command_vals;

  double avg_update_dur;
};
} // namespace passthrough_controller

#endif // PASSTHROUGH_CONTROLLER__PASSTHROUGH_CONTROLLER_HPP_
