#ifndef SAFETY_FORWARD_CONTROLLER__SAFETY_FORWARD_CONTROLLER_HPP_
#define SAFETY_FORWARD_CONTROLLER__SAFETY_FORWARD_CONTROLLER_HPP_

#include <atomic>
#include <float.h>
#include <memory>
#include <string>
#include <vector>

#include <urdf_parser/urdf_parser.h>

#include "controller_interface/chainable_controller_interface.hpp"
#include "rclcpp/subscription.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_buffer.hpp"
#include "std_msgs/msg/bool.hpp"
#include "std_msgs/msg/float64_multi_array.hpp"

#include <hector_ros_controllers_msgs/msg/safety_forward_controller_status.hpp>

// auto-generated by generate_parameter_library
#include <hector_ros_controllers/safety_forward_controller_parameters.hpp>

namespace safety_forward_controller
{

using CmdType = std_msgs::msg::Float64MultiArray;

class SafetyForwardController : public controller_interface::ChainableControllerInterface
{
public:
  SafetyForwardController();

  ~SafetyForwardController() override = default;

  controller_interface::InterfaceConfiguration command_interface_configuration() const override;

  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  controller_interface::CallbackReturn on_init() override;

  controller_interface::CallbackReturn
  on_configure( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::CallbackReturn
  on_activate( const rclcpp_lifecycle::State &previous_state ) override;

  controller_interface::CallbackReturn
  on_deactivate( const rclcpp_lifecycle::State &previous_state ) override;

protected:
  // Chainable controller API
  controller_interface::return_type
  update_reference_from_subscribers( const rclcpp::Time &time,
                                     const rclcpp::Duration &period ) override;

  controller_interface::return_type
  update_and_write_commands( const rclcpp::Time &time, const rclcpp::Duration &period ) override;

  std::vector<hardware_interface::CommandInterface> on_export_reference_interfaces() override;

  std::vector<hardware_interface::StateInterface> on_export_state_interfaces() override;

  void record_hold_positions();
  void publish_status();
  bool on_set_chained_mode( bool chained_mode ) override;

  // Parameter utilities
  void declare_parameters();
  controller_interface::CallbackReturn read_parameters();

  // Config
  std::vector<std::string> joints_;
  std::vector<std::shared_ptr<urdf::JointLimits>> joint_limits_;

  std::vector<std::string> command_interface_types_;
  std::vector<std::string> state_interface_types_;
  std::string interface_type_;

  // Safety timer
  std::atomic<bool> safety_engaged_{ false };
  int safety_timer_period_ms_{ 0 };
  rclcpp::TimerBase::SharedPtr safety_timer_;

  // E-stop
  rclcpp::Subscription<std_msgs::msg::Bool>::SharedPtr safety_estop_subscriber_;
  std::atomic<bool> estop_active_{ false };  // latest request (callback thread)
  std::atomic<bool> estop_engaged_{ false }; // actually applied in update() thread
  std::vector<double> hold_positions_;       // latched positions when e-stop engages

  // External command input (non-chained mode)
  realtime_tools::RealtimeBuffer<std::shared_ptr<CmdType>> rt_command_ptr_;
  rclcpp::Subscription<CmdType>::SharedPtr joints_command_subscriber_;

  // Status publisher (latched)
  rclcpp::Publisher<hector_ros_controllers_msgs::msg::SafetyForwardControllerStatus>::SharedPtr status_pub_;

  // Parameters
  std::shared_ptr<ParamListener> param_listener_;
  Params params_;
};

} // namespace safety_forward_controller

#endif // SAFETY_FORWARD_CONTROLLER__SAFETY_FORWARD_CONTROLLER_HPP_
